TABLE GMAXF(YYY,CCCRRRAAA,FFF)  'Maximum fuel use (GJ) per year'
                                                                      STRAW      WOOD      WOODWASTE BIOGAS    OTHERGAS   RETORTGAS SHALE    COAL PEAT     NATGAS
2016.DENMARK                                                          92884745   211677970 5588136   39799851
2016.GERMANY                                                          1010930549 513307043 148002229 254665913
2016.ESTONIA                                                          46493765   39572110  7509921   4675715                        92988000 eps  4550000
2016.LATVIA                                                           93723844   69203999  1077317   7301224
2016.LITHUANIA                                                        127823817  46599840  1706717   13264889
2016.NETHERLANDS                                                      176431557  6984583   33964401  106254252
2016.POLAND                                                           404766953  251337100 52638061  105588304
2016.FINLAND                                                          4393529    367696469 57599616  17813825  7322400
2016.SWEDEN                                                           58917605   435794800 16271873  27738546  8589600
2016.UNITED_KINGDOM                                                   2462798215 63012261  60939481  206527554
2016.NORWAY                                                           24068815   69586937  18357256  17947451  12999.9996
2017.ESTONIA                                                                                                                        92988000 eps  4550000
2018.ESTONIA                                                                                                                        92988000 eps  4550000
2019.ESTONIA                                                                                                                        92988000 eps  4550000
2020.ESTONIA                                                                                                                        92988000 eps  4550000
2021.ESTONIA                                                                                                                        92988000 eps  4521000
2022.ESTONIA                                                                                                                        92988000 eps  4492000
2023.ESTONIA                                                                                                                        92988000 eps  4463000
2024.ESTONIA                                                                                                                        92988000 eps  4434000
2025.ESTONIA                                                                                                                        59388000 eps  4405000
2026.ESTONIA                                                                                                                        59388000 eps  4376000
2027.ESTONIA                                                                                                                        59388000 eps  4347000
2028.ESTONIA                                                                                                                        59388000 eps  4318000
2029.ESTONIA                                                                                                                        59388000 eps  4289000
2030.ESTONIA                                                                                                                        25788000 eps  4260000
2031.ESTONIA                                                                                                                        25788000 eps  4620000
2032.ESTONIA                                                                                                                        25788000 eps  4980000
2033.ESTONIA                                                                                                                        25788000 eps  5340000
2034.ESTONIA                                                                                                                        25788000 eps  5700000
2035.ESTONIA                                                                                                                        25788000 eps  6060000
2036.ESTONIA                                                                                                                        25788000 eps  6420000
2037.ESTONIA                                                                                                                        25788000 eps  6780000
2038.ESTONIA                                                                                                                        25788000 eps  7140000
2039.ESTONIA                                                                                                                        25788000 eps  7500000
2040.ESTONIA                                                                                                                        25788000 eps  7860000
2041.ESTONIA                                                                                                                        25788000 eps  8220000
2042.ESTONIA                                                                                                                        25788000 eps  8580000
2043.ESTONIA                                                                                                                        25788000 eps  8940000
2044.ESTONIA                                                                                                                        25788000 eps  9300000
2045.ESTONIA                                                                                                                        25788000 eps  9660000
2046.ESTONIA                                                                                                                        25788000 eps  10020000
2047.ESTONIA                                                                                                                        25788000 eps  10380000
2048.ESTONIA                                                                                                                        25788000 eps  10740000
2049.ESTONIA                                                                                                                        25788000 eps  11100000
2050.ESTONIA                                                                                                                        25788000 eps  11460000
;
GMAXF(YYY,CCCRRRAAA,'STRAW')=GMAXF('2016',CCCRRRAAA,'STRAW');
GMAXF(YYY,CCCRRRAAA,'WOOD')=GMAXF('2016',CCCRRRAAA,'WOOD');
GMAXF(YYY,CCCRRRAAA,'WOODWASTE')=GMAXF('2016',CCCRRRAAA,'WOODWASTE');
GMAXF(YYY,CCCRRRAAA,'BIOGAS')=GMAXF('2016',CCCRRRAAA,'BIOGAS');
GMAXF(YYY,CCCRRRAAA,'OTHERGAS')=GMAXF('2016',CCCRRRAAA,'OTHERGAS');
GMAXF(YYY,CCCRRRAAA,'COAL')=GMAXF('2016',CCCRRRAAA,'COAL');





