SET S(SSS)  'Seasons in the simulation'                                                        
/                                                                                              
*S01,S02,S03,S04,S27,S28,S29,S30                                                               
*S09                                                                                           
*S09,S22,S32,S51                                                                               
S01*S52                                                                                        
/;                                                                                             
