PARAMETER SOLHFLH(AAA)  'Full load hours for solar heat (hours)'                                   
* NOT REAL DATA, DEMONSTRATION ONLY. Same data used for all regions as for Germany                 
/                                                                                                  
DK2_NoDH                                                                           703             
DK1_NoDH                                                                           703             
                                                                                                   
FinA                                                                               703             
DE4-E_A                                                                            1040            
DE4-N_A                                                                            1040            
DE4-S_A                                                                            1040            
DE4-W_A                                                                            1040            
NL_A                                                                               1040            
NO1_A1                                                                             703             
NO2_A1                                                                             703             
NO3_A1                                                                             703             
NO4_A1                                                                             703             
NO5_A1                                                                             703             
SE1A                                                                               703             
SE2A                                                                               703             
SE3A                                                                               703             
SE4A                                                                               703             
UK_A                                                                               1040            
EE_Rural                                                                           703             
LV_A                                                                               703             
LT_A                                                                               703             
PL_A                                                                               504.339051463168
AT_A                                                                               600             
CZ_A                                                                               524.924318869828
CH_A                                                                               618.768920282543
HU_A                                                                               610.898082744702
IT_A                                                                               733.80423814329 
SI_A                                                                               599.394550958628
SK_A                                                                               547.931382441978
DE_A                                                                               512.209889001009
FR_A                                                                               613.925327951564
ES_A                                                                               2190            
ES_CSP                                                                             2190            
PT_A                                                                               2190            
BE_A                                                                               2190            
LU_A                                                                               2190            
/;                                                                                                 
