PARAMETER STEPWISEPRICE_GMIDF(YYY,CCC,STEPWISEPRICE_FFF)   'Amount of fuel for which the fuel price from FUELPRICE      INC holds (GJ) (only used for setting amounts)'
/
2016                                                                                                               .    DENMARK                                         .    WOODCHIPS 11694400
2016                                                                                                               .    GERMANY                                         .    WOODCHIPS 50950700
2016                                                                                                               .    ESTONIA                                         .    WOODCHIPS 3761200
2016                                                                                                               .    LATVIA                                          .    WOODCHIPS 5441900
2016                                                                                                               .    LITHUANIA                                       .    WOODCHIPS 5047200
2016                                                                                                               .    NETHERLANDS                                     .    WOODCHIPS 5062300
2016                                                                                                               .    FINLAND                                         .    WOODCHIPS 34889600
2016                                                                                                               .    SWEDEN                                          .    WOODCHIPS 39433300
2016                                                                                                               .    UNITED_KINGDOM                                  .    WOODCHIPS 26670500
2016                                                                                                               .    NORWAY                                          .    WOODCHIPS 3745400
2016                                                                                                               .    POLAND                                          .    WOODCHIPS 27717300
2017                                                                                                               .    AUSTRIA                                         .    WOODCHIPS 3745400
2018                                                                                                               .    CZECHIA                                         .    WOODCHIPS 3745400
2019                                                                                                               .    SWITZERLAND                                     .    WOODCHIPS 3745400
2020                                                                                                               .    HUNGARY                                         .    WOODCHIPS 3745400
2021                                                                                                               .    ITALY                                           .    WOODCHIPS 3745400
2022                                                                                                               .    SLOVENIA                                        .    WOODCHIPS 3745400
2023                                                                                                               .    SLOVAKIA                                        .    WOODCHIPS 3745400
2024                                                                                                               .    GERMANY                                         .    WOODCHIPS 3745400
2025                                                                                                               .    FRANCE                                          .    WOODCHIPS 3745400
/;
STEPWISEPRICE_GMIDF(Y,C,STEPWISEPRICE_FFF)=STEPWISEPRICE_GMIDF('2016',C,STEPWISEPRICE_FFF);
