PARAMETER      TAX_DH(CCC,DHUSER) 'Consumers tax on heat consumption (Money/MWh)'  
/                                                                                  
$ontext                                                                            
DENMARK        0                                                                   
ESTONIA        0                                                                   
FINLAND        0                                                                   
GERMANY4       0                                                                   
LATVIA         0                                                                   
LITHUANIA      0                                                                   
NORWAY         0                                                                   
POLAND         0                                                                   
RUSSIA         0                                                                   
SWEDEN         0                                                                   
BELARUS        0                                                                   
ESTONIA        0                                                                   
LATVIA         0                                                                   
LITHUANIA      0                                                                   
POLAND         0                                                                   
AUSTRIA        0                                                                   
CZECH_REPUBLIC 0                                                                   
SWITZERLAND    0                                                                   
HUNGARY        0                                                                   
ITALY          0                                                                   
SLOVENIA       0                                                                   
SLOVAKIA       0                                                                   
GERMANY        0                                                                   
FRANCE         0                                                                   
$offtext                                                                           
/;                                                                                 
                                                                                   
