TABLE FKMAX(YYY,CCCRRRAAA,FFF)     'Maximum capacity by fuel per year (MW)'                                                           
                                                                            NATGAS       MUNIWASTE     WASTEHEAT WOOD        WOODWASTE
2020.AT                                                                                                10        0                    
2030.AT                                                                                                100                            
2040.AT                                                                                                100                            
2050.AT                                                                                                100                            
;                                                                                                                                     
