TABLE FMAXINVESTNA(YYY,FFF)        'Maximum investment by year and fuel type for each year simulated (MW)(aggregated countries)'                                                           
                                                                                                                                 NATGAS       MUNIWASTE     WASTEHEAT WOOD        WOODWASTE
2020                                                                                                                                                        10                             
2030                                                                                                                                                        100                            
2040                                                                                                                                                        100                            
2050                                                                                                                                                        100                            
;                                                                                                                                                                                          
