PARAMETER GROWTHCAP(C,GGG)  'Maximum model generated capacity increase (MW) from one year to the next';
GROWTHCAP(C,K5_GNR_GEOTHERMAL_2020) =10;                                                               
GROWTHCAP(C,K5_GNR_GEOTHERMAL_2030) =100;                                                              
GROWTHCAP(C,K5_GNR_GEOTHERMAL_2040) =100;                                                              
GROWTHCAP(C,K5_GNR_GEOTHERMAL_2050) =100;                                                              
