* PARAMETER GKNMAX holds the maximum capacities of those production technologies           
* for which investments are allowed. If not any value is specified in this table           
* the default value is inf.                                                                
* Units: MW.                                                                               
GKNMAX('2020','AT_A,'K5_GNR_GEOTHERMAL_2020')=                                   10   ;    
GKNMAX('2030','AT_A,'K5_GNR_GEOTHERMAL_2030')=                                   100  ;    
GKNMAX('2040','AT_A,'K5_GNR_GEOTHERMAL_2040')=                                   100  ;    
GKNMAX('2050','AT_A,'K5_GNR_GEOTHERMAL_2050')=                                   100  ;    
*GKNMAX(YYY,AAA,GGG)=                                                            INF  ;    
*GKNMAX('2050','DK2_Large','GNR_HP_ELEC_GROUND-WTR_COP-410_LS-4-MW_Y-2050')=     200  ;    
