PARAMETER XMAXINV(IRRRE,IRRRI)   'Max investment in transmission capacity between two regions for each simulated year(each 5th year)'                           
/                                                                                                                                                               
$ontext                                                                                                                                                         
AT                                                                                                                                      .    CZ   1000          
AT                                                                                                                                      .    CH   1700          
AT                                                                                                                                      .    HU   1200          
AT                                                                                                                                      .    IT   1605          
AT                                                                                                                                      .    SI   2200          
AT                                                                                                                                      .    DE   7500          
CH                                                                                                                                      .    AT   1700          
CH                                                                                                                                      .    DE   4100          
CH                                                                                                                                      .    FR   5200          
CH                                                                                                                                      .    IT   3700          
CZ                                                                                                                                      .    AT   1200          
CZ                                                                                                                                      .    DE   2000          
CZ                                                                                                                                      .    PO   800           
CZ                                                                                                                                      .    SK   1100          
DE                                                                                                                                      .    AT   7500          
DE                                                                                                                                      .    CH   6500          
DE                                                                                                                                      .    CZ   2600          
DE                                                                                                                                      .    FR   5800          
DE                                                                                                                                      .    PO   3500          
ES                                                                                                                                      .    PT   1000          
ES                                                                                                                                      .    FR   1000          
FR                                                                                                                                      .    CH   3800          
FR                                                                                                                                      .    DE   5800          
FR                                                                                                                                      .    IT   4350          
FR                                                                                                                                      .    ES   1000          
HU                                                                                                                                      .    AT   800           
HU                                                                                                                                      .    SI   1200          
HU                                                                                                                                      .    SK   2000          
IT                                                                                                                                      .    AT   1335          
IT                                                                                                                                      .    CH   6000          
IT                                                                                                                                      .    FR   2160          
PO                                                                                                                                      .    CZ   600           
PO                                                                                                                                      .    DE   3000          
PO                                                                                                                                      .    SK   990           
PT                                                                                                                                      .    ES   1000          
SI                                                                                                                                      .    AT   2200          
SI                                                                                                                                      .    HU   1200          
SK                                                                                                                                      .    CZ   2100          
SK                                                                                                                                      .    HU   2000          
SK                                                                                                                                      .    PO   990           
$offtext                                                                                                                                                        
/;                                                                                                                                                              
                                                                                                                                                                
